export const FETCH_DOGS = "FETCH_DOGS"
export const FETCH_FEMALE_DOGS = "FETCH_FEMALE_DOGS"
export const FETCH_MALE_DOGS = "FETCH_MALE_DOGS"
export const FETCH_DOG = "FETCH_DOG"
export const FETCH_ONE_DOG = "FETCH_ONE_DOG"

export const FETCH_USER = "FETCH_USER"
export const CREATE_USER = "CREATE_USER"
export const LOGGED_USER = "LOGGED_USER"
export const UPDATE_WALLET = "UPDATE_WALLET"